/* <<<{ */

import { Color } from "../lib/Colors.js";
import { Vec2, Vec3, Vec4 } from "../lib/TSM.js";
import _ from "../lib/Underscore.js";

/*
    List Utility Functions
*/

/* Concatenates a list onto itself repeatedly */
export function repeat<T>(list: T[], times: number): T[] {
  let out: T[] = [];
  for (let i = 0; i < times; i++) {
    out = out.concat(list);
  }
  return out;
}

export function flattenListOfVec(listofVec: Vec3[] | Vec4[]): number[] {
  const out: number[] = new Array<number>();
  if (listofVec[0] instanceof Vec3) {
    (listofVec as Vec3[]).forEach((e) => out.push(e.x, e.y, e.z));
  } else if (listofVec[0] instanceof Vec4) {
    (listofVec as Vec4[]).forEach((e) => out.push(e.x, e.y, e.z, e.w));
  }
  return out;
}

// You will likely want to add extra helper functions throughout your project.
// Feel free to do so here!

/**
 * Exports geometry to OBJ format
 * @param positions 
 * @param indices
 * @returns OBJ file as string
 */

//Function that assumes the positions array is a flat array of Vec4 (x, y, z, w) and the indices array is a flat array of vertex indices for triangles.
export function exportToOBJ(positions: Float32Array, indices: Uint32Array): string {
  let obj = "# Menger Sponge Geometry\n"; // OBJ file header comment
  obj += "# Generated by Menger Sponge Renderer\n\n";

// Write vertex positions (v x y z)
  for (let i = 0; i < positions.length; i += 4) {
    const x = positions[i];
    const y = positions[i + 1];
    const z = positions[i + 2];
    obj += `v ${x} ${y} ${z}\n`;
  }

  obj += "\n";

 // Write face definitions (f v1 v2 v3)  
  for (let i = 0; i < indices.length; i += 3) {
    const v1 = indices[i] + 1;
    const v2 = indices[i + 1] + 1;
    const v3 = indices[i + 2] + 1;
    obj += `f ${v1} ${v2} ${v3}\n`;
  }

  return obj;
}
